### ISSUE TITLE
Cellulose needs update

### ISSUE THREAD

**Issue by mcglenn07** [GravityPDF/gravity-pdf#1262] opened 2021-04-13 01:40 UTC
**Description**
Borders disappear when updating settings tab.

**Step To Reproduce**
1. Choose Cellulose template and view a PDF
2. Ensure the "Hide Border" Checkbox is not ticked
3. Update any settings ie. rename template, upload image/logo

**Expected behavior**
The borders should stay visible if the "Hide Border" Checkbox is unticked

**Screenshot**
![image](https://user-images.githubusercontent.com/35588091/114490168-f4954880-9c46-11eb-977d-9a75e297c27c.png)

![image](https://user-images.githubusercontent.com/35588091/114490344-4211b580-9c47-11eb-9757-35b486d24089.png)

**Comment by jakejackson1** [comment] 2021-04-13 02:15
@mcglenn07 could you include a screenshot please?

**Comment by jestonihpi** [comment] 2021-04-13 10:13
This bug is caused by the if condition for `$settings['cell_hide_border']`.  Testing if this variable is set or not, in which the value is either '' or 1 - thus returns `true`.

**Comment by jakejackson1** [comment] 2021-04-13 22:46
@jestonihpi could you prepare the appropriate fix for this please?

**Comment by jakejackson1** [comment] 2021-04-20 06:06
Fixed in https://github.com/GravityPDF/gravity-pdf/pull/1268

**Closed by jakejackson1** 2021-04-20 06:06 UTC
Labels: Backend
