### ISSUE TITLE
call External css file

### ISSUE THREAD

**Issue by odyright** [GravityPDF/gravity-pdf#491] opened 2016-09-08 17:50 UTC
how to call external css file in gravity pdf custom template... instead of styling in the same template?

**Comment by odyright** [comment] 2016-09-08 17:58
I tried echo '.. but it doesn't work!

**Comment by jakejackson1** [comment] 2016-09-08 22:12
Closing because this is not a bug report. [Use our support system](https://gravitypdf.com/support/) for help.

**Closed by jakejackson1** 2016-09-08 22:12 UTC
